# Site settings
remote_theme: "mmistakes/minimal-mistakes"
title: Yasas Gamagedara

minimal_mistakes_skin: "mint"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Site Author
author:
  name             : 
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "PhD Student"
  location         : "Starkville, MS"
  email            : "kg1603@msstate.edu"
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "kanthake"
  foursquare       :
  github           : "kanthsaz"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : "kanthsaz"
  lastfm           :
  linkedin         : "kanthakeyasas"
  pinterest        :
  soundcloud       :
  stackoverflow    : #8371691/kani # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "kanthake"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
  research_gate    : "Yasas-Gamagedara"

# Build settings
include: ["_pages"]
exclude: ["README.md"]
exclude: [vendor]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true

atom_feed:
  hide: true
